### ISSUE TITLE
CSB Javascript Not Found

### ISSUE THREAD

**Issue by netclectic** [Blazored/LocalStorage#24]
After updating my CSB app to v2.0.6 for Preview 7 I started seeing an issue on startup... 

```
Microsoft.JSInterop.JSException: Could not find 'LocalStorage' in 'window.Blazored'.
```

Adding the script tag to my index.html, re the instructions for SSB, resolved the issue.

**Comment by dinonovak** [comment]
I can confirm that upgrading to Blazor Preview7 requires manual add on script tag to function properly.

**Comment by chrissainty** [comment]
@netclectic - Is this still the case with v2.0.7?
@dinonovak - Which version are you using and is that client-side Blazor or server-side?

**Comment by netclectic** [comment]
The problem is resolved with v2.0.7.

Thanks!

**Comment by chrissainty** [comment]
Great stuff. I’m going to go ahead and close the issue as things seem to be working as expected now.

**Comment by joshhubers** [comment]
First, thanks for the fantastic repo!

I'm receiving this error also. Using docker image dotnet/core/3.0.100-preview8-disco with localstorage version 2.0.11

```Microsoft.JSInterop.JSException: Could not find 'blazoredLocalStorage' in 'window'.```

**Comment by joshhubers** [comment]
I'm still receiving this issue in the browser and updated the _Host file to:

```<script src="_content/Blazored.LocalStorage/blazored-localstorage.js"></script>```

Running the the latest LocalStorage - 2.0.11

Running core preview8 in docker image - core/sdk:3.0.100-preview8-disco

I get a 404 for the js file in the browser.

Thanks!

**Comment by chrissainty** [comment]
@joshhubers Have you tried a clean/re-build/clear of browser cache. I've had a lot of people have this issue and one of those sorts it out. 

There are some issues with the new Razor Class Library right now. So it might be best to just manually copy the JS file from this repo into your solution.

**Comment by thild** [comment]
I have a blazorwasm app but served by a webapi. In order to get Blazored.LocalStorage working I had to add this to Blazored.LocalStorage.csproj.
```
  <ItemGroup>
    <!-- .js/.css files will be referenced via <script>/<link> tags; other content files will just be included in the app's 'dist' directory without any tags referencing them -->
    <EmbeddedResource Include="wwwroot\**\*.js" LogicalName="blazor:js:%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="wwwroot\**\*.css" LogicalName="blazor:css:%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="wwwroot\**" Exclude="**\*.js;**\*.css" LogicalName="blazor:file:%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
```
This will copy all embedded resources to bin/Debug/netstandard2.0/dist/_content/Blazored.LocalStorage/* so Kestrel can serve.
Doing this the tag `<script src="_content/Blazored.LocalStorage/blazored-localstorage.js"></script>` is added automatically by Blazor in index.html.
This not affect BlazorClientSide sample app.

I create a pull request #29.

**Comment by chrissainty** [comment]
@thild This code is now legacy and not the way class libraries need to work going forward. As of right now the situation is this. Both JS and CSS in Razor Class libraries gets included in host projects correctly at development time. If you're not seeing this then see my comment above explaining the steps to go through to get things working. 

However, both for client-side Blazor and server-side Blazor there is an issue with publishing which stop static assets being included correctly, this is going to be fixed in Preview 9 (I hope!).

**Comment by thild** [comment]
@chrissainty Thanks for clarification. Investigating further I found that is a known Blazor issue https://github.com/aspnet/AspNetCore/issues/13122. The workaround mentioned there is run the project in development environment.
`ASPNETCORE_ENVIRONMENT=Development dotnet run`
or setup `Properties/launchSettings.json`
```
{
    "profiles": {
        "ServerProjectName": {
            "commandName": "Project",
            "launchBrowser": true,
            "environmentVariables": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "applicationUrl": "http://localhost:5000/"
        }
    }
}
```
However, you might consider keeping the EmbeddedResource workaround in `.cpsproj` until the Blazor team resolves this issue, as this does not affect the new way of referencing static assets.

**Comment by chrissainty** [comment]
I've now pushed a new version of the package which no longer needs a JavaScript file. This should completely remove the issue. Please give it a go and let me know if you have any issues.

**Comment by thild** [comment]
I tried the new version. Removed reference to js and everything is working. Nice solution. Thanks.
